# Generated by Django 4.2.3 on 2023-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specilazion', models.CharField(max_length=50)),
                ('expirence', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
