# Generated by Django 4.2.3 on 2023-09-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=80)),
                ('patient_age', models.CharField(max_length=80)),
                ('patient_email', models.EmailField(max_length=254)),
                ('appointment_cause', models.CharField(max_length=50)),
                ('appointment_date', models.CharField(max_length=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor_details')),
            ],
        ),
    ]
